### ISSUE TITLE
may be not work for ver.2.30.20?

### ISSUE THREAD

**Issue by yumusb** [acecilia/OpenWRTInvasion#135] opened 2022-05-24 07:31 UTC
I had try it many times in chinese version 2.30.20.

**Comment by devidlis123** [comment] 2022-06-19 14:52
Hello, mine is the same version. No solution?

**Comment by Iven-hoo** [comment] 2022-07-16 15:14
i got the problem by printing out the code information. The problem is that the new version of 2.30.20 api interface has changed, and the parameters may have been adjusted

**Comment by acecilia** [comment] 2022-09-08 21:34
Closing this as duplicate of https://github.com/acecilia/OpenWRTInvasion/issues/141

**Closed by acecilia** 2022-09-08 21:34 UTC
